### ISSUE TITLE
Intro article secure-your-mac.md rendered as HTML source in browser

### ISSUE THREAD

**Issue by jlmuir** [sarfata/voodooprivacy#15]
In `README.md`, in the section titled `The firewall`, it says:

```
For more information, read the introduction article: http://www.sarfata.org/posts/secure-your-mac.md
```

When I open that link in a web browser, it displays HTML source code, not the rendered page.  I tested this on macOS Sierra in the latest Safari, Google Chrome, and Firefox, and on iOS in Safari.

**Comment by sarfata** [comment]
thanks for pointing this out. fixed!
